import React from 'react';
import {
  Grid,
  Layers,
  Warehouse,
  Home,
  Sofa,
  Recycle,
  Trash2,
  Bike,
  Dumbbell,
  Shield,
  Fence,
  Trees,
  Lightbulb,
  UtilityPole,
  Smile,
  Heart,
  Sparkles,
  MapPin,
  Activity,
  Footprints,
  Sun,
  Umbrella,
  Tent,
  Landmark,
  Castle,
  Sprout,
  Flower2,
  Construction,
  Compass,
  Hammer,
  Wrench,
  Package,
  Truck,
  Map,
  Ruler,
  Settings,
  Leaf,
  Paintbrush,
  UserCheck,
  Users,
  Building2,
  Scissors,
  Flame,
  Droplet,
  Scale,
  Globe,
  Briefcase,
  Award,
  BookOpen,
  Clock,
  HardHat,
  Phone,
  Info,
  Lock,
  QrCode,
  Wifi,
  BatteryCharging
} from 'lucide-react';

export const ICON_MAP: Record<string, React.ComponentType<any>> = {
  Grid,
  Layers,
  Warehouse,
  Home,
  Sofa,
  Recycle,
  Trash2,
  Bike,
  Dumbbell,
  Shield,
  Fence,
  Trees,
  Lightbulb,
  UtilityPole,
  Smile,
  Heart,
  Sparkles,
  MapPin,
  Activity,
  Footprints,
  Sun,
  Umbrella,
  Tent,
  Landmark,
  Castle,
  Sprout,
  Flower2,
  Construction,
  Compass,
  Hammer,
  Wrench,
  Package,
  Truck,
  Map,
  Ruler,
  Settings,
  Leaf,
  Paintbrush,
  UserCheck,
  Users,
  Building2,
  Scissors,
  Flame,
  Droplet,
  Scale,
  Globe,
  Briefcase,
  Award,
  BookOpen,
  Clock,
  HardHat,
  Phone,
  Info,
  Lock,
  QrCode,
  Wifi,
  BatteryCharging
};

export const AVAILABLE_ICONS = [
  { name: 'Grid', label: '기본 그리드 (전체)' },
  { name: 'Layers', label: '레이어 (복합시설)' },
  { name: 'Umbrella', label: '파라솔/그늘막 (파고라)' },
  { name: 'Tent', label: '야외 텐트 (그늘막)' },
  { name: 'Warehouse', label: '가루쉘터 (대형창고)' },
  { name: 'Landmark', label: '전통 전각 (정자/기품)' },
  { name: 'Castle', label: '고전 건축 (정자/성곽)' },
  { name: 'Home', label: '전통 기와 (쉼터)' },
  { name: 'Sofa', label: '옥외용 벤치 (의자)' },
  { name: 'Recycle', label: '리사이클 (분리수거)' },
  { name: 'Trash2', label: '휴지통 (위생수거)' },
  { name: 'Bike', label: '자전거 (보관대)' },
  { name: 'Dumbbell', label: '덤벨 (야외운동)' },
  { name: 'Activity', label: '활동성 (운동에너지)' },
  { name: 'Heart', label: '헬스케어 (심장)' },
  { name: 'Trees', label: '조경 수목 (자연)' },
  { name: 'Sprout', label: '새싹/화단 (플랜터)' },
  { name: 'Flower2', label: '꽃/화분대 (조경)' },
  { name: 'Fence', label: '경계 울타리 (펜스)' },
  { name: 'Shield', label: '안전 가드 (볼라드)' },
  { name: 'Construction', label: '공사/안전 (안전시설)' },
  { name: 'Lightbulb', label: '경관 전구 (조명)' },
  { name: 'UtilityPole', label: '기둥 구조 (시설)' },
  { name: 'Smile', label: '미소 쉼터 (휴게)' },
  { name: 'Sparkles', label: '우수 제품 (추천)' },
  { name: 'MapPin', label: '랜드마크 핀 (인도)' },
  { name: 'Footprints', label: '보행 산책로 (인도)' },
  { name: 'Sun', label: '친환경 태양광 (스마트)' },
  { name: 'HardHat', label: '안전모 (시공현장)' },
  { name: 'Wrench', label: '렌치 (조립설치)' },
  { name: 'Hammer', label: '망치 (직접공정)' },
  { name: 'Ruler', label: '설계자 (기술도면)' },
  { name: 'Compass', label: '나침반 (도면설계)' },
  { name: 'Leaf', label: '나뭇잎 (친환경재)' },
  { name: 'Flame', label: '고온탄화 (열처리목)' },
  { name: 'Droplet', label: '방수제 (에스테인)' },
  { name: 'Paintbrush', label: '브러쉬 (표면도장)' },
  { name: 'Scissors', label: '정밀절삭 (CNC레이저)' },
  { name: 'Scale', label: '정밀중량 (강도검증)' },
  { name: 'Building2', label: '빌딩도시 (조경건설)' },
  { name: 'Truck', label: '화물트럭 (신속배송)' },
  { name: 'Package', label: '자재적재 (창고보관)' },
  { name: 'Map', label: '배치도 (현장배치)' },
  { name: 'Award', label: '우수조달 (정식인증)' },
  { name: 'BookOpen', label: '시방서 (기술규격)' },
  { name: 'Clock', label: '납기준수 (신속설치)' },
  { name: 'UserCheck', label: '신뢰인증 (대표이사)' },
  { name: 'Users', label: '협력기업 (공동참여)' },
  { name: 'Briefcase', label: '관공서 (공공납품)' },
  { name: 'Globe', label: '해외원목 (고급자재)' },
  { name: 'Phone', label: '고객상담 (문의전화)' },
  { name: 'Info', label: '안내사인 (안내판)' },
  { name: 'Lock', label: '안전보관 (함체보안)' },
  { name: 'QrCode', label: '스마트QR (디지털판)' },
  { name: 'Wifi', label: '와이파이 (스마트쉘)' },
  { name: 'BatteryCharging', label: '스마트벤치 (충전소)' }
];
